import { useEffect,useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {  MeshPhysicalMaterial } from 'three'



// useGLTF.preload('./models/truck.gltf')
// useGLTF.preload('./models/vehicle.glb')
// useGLTF.preload('./models/bike.gltf')
// useGLTF.preload('./models/white_simple_car_01.glb')
// useGLTF.preload('./models/truck.gltf')
// useGLTF.preload('/sweep/sweep.glb')
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Model via KrStolorz on Sketchfab, CC-BY-4.0
// https://sketchfab.com/3d-models/low-poly-volkswagen-beetle-f680ad7e98e445eaafed1a70f2c53911
const bodyMaterial = new MeshPhysicalMaterial( {
  color: 0xaaaaaa, metalness: 0.5, roughness: 1.5, clearcoat: 1.0, clearcoatRoughness: 0.43, sheen: 0.5
} );
const Car = ({url,position,scale,rotation}) => {
    const ref = useRef(null);
    // const { nodes, materials } = useGLTF('/Beetle.glb')
//   const { nodes, materials } = useGLTF('/Beetle.glb')
//   const { scene: bike} = useGLTF('/models/bike.gltf')
//   const { scene: bike} = useGLTF('/models/bike.glb')
//   const { scene: white_simple_car_01} = useGLTF('/models/white_simple_car_01.gltf')

  const gltf = useGLTF(url)
  const scene  = gltf.scene.clone(true)
  useEffect(()=>{
    if(ref.current){
        ref.current.traverse(o=>{
            o.material = bodyMaterial//materials["Reverse lights"]
        })
    }
  },[])
//   const trunk_gltf = useLoader(GLTFLoader, '/models/truck.gltf')
//   console.log(vehicle)
  return  <primitive ref={ref} object={scene} position={position} rotation={rotation} scale={[scale,scale,scale]}/> 


  
}


const Cars = ()=>{
    return <group>
        <Car url={'./models/truck.gltf'} position={[12, 3, 0]} scale={0.024} rotation={[Math.PI/2,Math.PI,0]}/>
        <Car url={'./models/white_simple_car_01.glb'} position={[-5, 3, 0]} scale={1} rotation={[Math.PI/2,-Math.PI/2,0]}/>
        {/* <Car url={'./models/bike.glb'} position={[-5, -3, 0]} scale={0.024} rotation={[Math.PI/2,-Math.PI/2,0]}/> */}
        </group>
}
export default Cars
